### PR TITLE
Write glyph advance as unsigned instead of signed Int16

### PR DESCRIPTION
**Pull request by hklindworth**
Advance cannot be negative, but can be up to 65535

https://www.freetype.org/freetype2/docs/tutorial/step2.html

### CODE REVIEW

**Comment by ncannasse** [comment]
Please look at #59

**Comment by hklindworth** [comment]
Sorry, I forgot to check out that other pull request before.

Nevertheless, to me it still seems the SWF-spec is wrong and Flash is handling the advance as UInt16.
I have found no fonts with negative advance. There are multiple fonts which have an advance above 32768, including Ubuntu and Dejavu Sans which are used in the Starling demo app: https://github.com/openfl/starling
These are wide characters like ‱ (char code 8241, https://unicode-table.com/en/search/?q=8241).

E.g. this is how it looks with 35584 advance:
image

This is how it looks when reduced to 32767 advance (too narrow):
image

**Comment by ncannasse** [comment]
Ok, best would then be  `if( v < 0 ) 0 else if( v > 0xFFFFF ) 0xFFFFF else v` no ?

**Comment by hklindworth** [comment]
This will also work, but 0xFFFF instead 0xFFFFF

**Comment by ncannasse** [comment]
Can you fix your PR accordingly ?

Le 4 sept. 2017 11:06, "Hendrik Klindworth" <notifications@github.com> a
écrit :

**Comment by hklindworth** [comment]
alright, changed it

**Pull request merged**
