### PR TITLE
Bmp patches

### PR DESCRIPTION
**Pull request by azrafe7**
This PR aims to improve BMP support, and adds some convenience methods to manipulate the data:

 - `Data.header` contains more info about the binary data
 - support for `topToBottom` bmps is added
 - `extractBGRA/ARGB()` methods to convert from binary representation (which is 24bpp BGR)
 - `buildFromBGRA/ARGB()` methods to build a `bmp.Data` from these common formats
 - `bmp.Reader/Writer()` have been modified to accomodate for the mentioned features
 - tests

Note also that some things have been removed:
 - conditional compilation for haxe 2 (readInt32/31)
 - to/fromBitmap for flash

The latter can easily be replicated with the `extract/build` functions.

(ref #26)

### CODE REVIEW

**Comment by azrafe7** [comment]
@ncannasse: maybe I got ARGB and BGRA inverted, can you please check that?

**Comment by azrafe7** [comment]
Ok, with further tests I think I _may_ have got it right in the end...

but some doubts remain, related to [this](https://github.com/azrafe7/format/blob/5e5fe56acc0bf009c76e49d5c6ca6714bb15fa49/tests/bmp/Tests.hx#L196) and [this](https://github.com/azrafe7/format/blob/5e5fe56acc0bf009c76e49d5c6ca6714bb15fa49/tests/bmp/Tests.hx#L260-L271). (not sure if only flash-related)

**Comment by ncannasse** [comment]
Could you resubmit the PR without the lena.bmp which takes 780KB (using something smaller) ? I like to keep the repos as much small/clean as possible :) Everything else looks good.

**Comment by azrafe7** [comment]
Are you ok if I resize lena.bmp to take ~115k?

**Comment by ncannasse** [comment]
Sure

**Comment by azrafe7** [comment]
@ncannasse, is this good to go now?

**Comment by ncannasse** [comment]
NG, you need to resubmit your PR without your 780KB commit or else it will go into the github history :)

**Pull request closed without merging**
